INSERT INTO Locations (Location) VALUES
	('Perimeter'),
	('Center');

INSERT INTO Department (Department) VALUES
	('Bakery'),
	('Dairy'),
	('Deli and Foodservice'),
	('Floral'),
	('Frozen'),
	('GM'),
	('Grocery'),
	('Seafood');


INSERT INTO Category (Category) VALUES
	('Bakery Bread'),
	('In Store Bakery'),
	('Cheese'),
	('Cream or Creamer'),
	('Cultured'),
	('Refrigerated Baking'),
	('Self Service Deli Cold'),
	('Service Deli'),
	('Bouquets and Cut Flowers'),
	('Gifts'),
	('Plants'),
	('Frozen Bake'),
	('Frozen Breakfast'),
	('Frozen Desserts or Fruit and Toppings'),
	('Frozen Juice'),
	('Audio Video'),
	('Housewares'),
	('Insect and Rodent'),
	('Kitchen Accessories'),
	('Laundry'),
	('Baking Ingredients'),
	('Spices'),
	('Stuffing Products'),
	('Frozen Shellfish'),
	('Other Seafood');
	
	INSERT INTO SubCategory (SubCategory) VALUES
	('Bagels'),
	('Baking or Breading Products'),
	('English Muffins or Biscuits'),
	('Flatbreads'),
	('Breakfast Cake or Sweet Roll'),
	('Cakes'),
	('Pies'),
	('Seasonal'),
	('Cheese Sauce'),
	('Specialty Cheese'),
	('Dairy Alternative Creamer'),
	('Whipping Creams'),
	('Cottage Cheese'),
	('Refrigerated Breads'),
	('Refrigerated English Muffins and Biscuits'),
	('Refrigerated Hand Held Sweets'),
	('Refrigerated Pie Crust'),
	('Refrigerated Sweet Breakfast Baked Goods'),
	('Beverages'),
	('Cheese All Other'),
	('Cheese American'),
	('Bouquets and Cut Flowers'),
	('Gifts'),
	('Plants'),
	('Bread or Dough Products Frozen'),
	('Breakfast Cake or Sweet Roll Frozen'),
	('Frozen Breakfast Entrees'),
	('Frozen Breakfast Sandwich'),
	('Frozen Egg Substitutes'),
	('Frozen Syrup Carriers'),
	('Pies Frozen'),
	('Frozen Apple Juice'),
	('Frozen Fruit Drink Mixers'),
	('Frozen Fruit Juice All Other'),
	('Audio'),
	('Video DVD'),
	('Video VHS'),
	('Bedding'),
	('Candles'),
	('Collectibles and Gifts'),
	('Flashlights'),
	('Frames'),
	('Indoor Repellants or Traps'),
	('Outdoor Repellants or Traps'),
	('Kitchen Accessories'),
	('Bleach Liquid'),
	('Bleach Powder'),
	('Fabric Softener Liquid'),
	('Fabric Softener Sheets'),
	('Dry or Canned Milk'),
	('Food Coloring'),
	('Salt Cooking or Edible or Seasoned'),
	('Salt Substitute'),
	('Seasoning Dry'),
	('Stuffing Products'),
	('Frozen Shellfish'),
	('All Other Seafood'),
	('Prepared Seafood Entrees'),
	('Seafood Salads'),
	('Smoked Fish'),
	('Seafood Breading Sauces Dips');




INSERT INTO Locations_x_ref (LocationId, DepartmentId, CategoryId, SubCategoryId) VALUES
	('1', '1', '1', '1'),
	('1', '3', '7', '19'),
	('1', '4', '9', '22'),
	('2', '5', '12', '25'),
	('2', '6', '16', '35'),
	('2', '6', '16', '36'),
	('1', '8', '24', '56'),
	('1', '8', '25', '57'),
	('1', '8', '25', '58'),
	('1', '1', '1', '1'),
	('1', '3', '7', '19'),
	('1', '4', '9', '22'),
	('2', '5', '12', '25');



	
INSERT INTO SKU_v2 (SKUId, Name, LocationId, DepartmentId, CategoryId, SubCategoryId) VALUES
	('1', 'SKUDESC1', '1', '1', '1', '1'),
	('2', 'SKUDESC2', '1', '3', '7', '19'),
	('3', 'SKUDESC3', '1', '4', '9', '22'),
	('5', 'SKUDESC5', '2', '5', '12', '25'),
	('7', 'SKUDESC7', '2', '6', '16', '35'),
	('8', 'SKUDESC8', '2', '6', '16', '36'),
	('10', 'SKUDESC10', '1', '8', '24', '56'),
	('11', 'SKUDESC11', '1', '8', '25', '57'),
	('12', 'SKUDESC12', '1', '8', '25', '58'),
	('14', 'SKUDESC14', '1', '1', '1', '1'),
	('15', 'SKUDESC15', '1', '3', '7', '19'),
	('16', 'SKUDESC16', '1', '4', '9', '22'),
	('18', 'SKUDESC18', '2', '5', '12', '25');